class HandoffDocument < ApplicationRecord
  belongs_to :repository

  validates :overview, presence: true
  validates :features, presence: true

  before_save :generate_markdown

  private

  def generate_markdown
    self.generated_markdown = <<~MARKDOWN
      # #{repository.name} Handoff Document

      ## Repository

      #{repository.url}

      ## Project

      #{repository.project.name}

      ## Overview

      #{overview}

      ## Main Features

      #{features}

      ## Database Notes

      #{database_notes.presence || "Not documented yet."}

      ## Environment Variables

      #{environment_notes.presence || "Not documented yet."}

      ## Setup Notes

      #{setup_notes.presence || "Not documented yet."}

      ## Operation Notes

      #{operation_notes.presence || "Not documented yet."}

      ## Risks / Handoff Warnings

      #{risks.presence || "Not documented yet."}

      ---

      Generated by CodeHandoff Notes.
    MARKDOWN
  end
end